export const cesiumEntityTypes = [
  'billboard',
  'box',
  'corridor',
  'cylinder',
  // 'description',
  'ellipse',
  // 'ellipsoid',
  'label',
  'model',
  'tileset',
  // 'orientation',
  'path',
  'plane',
  'point',
  'polygon',
  'polyline',
  // 'polylineVolume',
  // 'position',
  // 'properties',
  'rectangle',
  // 'viewFrom',
  'wall'
]
